# Generated by Django 4.1.7 on 2023-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_course',
            field=models.IntegerField(blank=True, null=True, verbose_name='оплаченные курсы'),
        ),
    ]
