# Generated by Django 4.1.7 on 2023-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_payment_pay_lesson_alter_payment_pay_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Success', models.BooleanField(default=False)),
                ('ErrorCode', models.PositiveIntegerField(default=0)),
                ('TerminalKey', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('PaymentId', models.CharField(max_length=100)),
                ('OrderId', models.CharField(max_length=100)),
                ('Amount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
