# Generated by Django 4.1.7 on 2023-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='PaymentURL',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
