# Generated by Django 4.1.7 on 2023-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentlog_paymenturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='Amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='ErrorCode',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='OrderId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='PaymentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='PaymentURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='TerminalKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
