# Generated by Django 4.1.7 on 2023-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_paymentlog_amount_alter_paymentlog_errorcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
