# Generated by Django 4.1.7 on 2023-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_paymentlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='check_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
