# Generated by Django 4.1.7 on 2023-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=100, verbose_name='цена курса'),
        ),
    ]
